version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eurotunnel_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      # Attention ici, le port externe vient du .env, le port interne reste 5432
      - "${DB_PORT}:5432"